### ISSUE TITLE
EOFError when loading metadata

### ISSUE THREAD

**Issue by Ferase** [IraKorshunova/folk-rnn#10]
Hello!

I just started setting this up, but after running all of the setup commands, I get an EOFError when trying to load the default metadata pickle (folkrnn_v2.pkl).

Here's the traceback plus the warnings beforehand:

```
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\parkm\Anaconda3\envs\frnn\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "sample_rnn.py", line 38, in <module>
    metadata = pickle.load(f)
EOFError
```

Is there a step I'm missing to installing this? I'm running Anaconda 4.8.2 with Python 2.7 on Windows 10 and I'm installing this on a fresh environment just as the guide on the readme says.

Thanks!

**Comment by baodad** [comment]
Same issue here.  I went one step further and tried 'conda install m2w64-toolchain' which completed successfully.
Now, running `python sample_rnn.py --terminal metadata/folkrnn_v2.pkl`
I get:
`You can find the C code in this temporary file: c:\Users\me\appdata\local\temp\theano_compilation_error_qafi08
Traceback (most recent call last):
  File "sample_rnn.py", line 3, in <module>
    import theano
  File "C:\Users\me\Anaconda3\envs\py2\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Users\me\Anaconda3\envs\py2\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Users\me\Anaconda3\envs\py2\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Users\me\Anaconda3\envs\py2\lib\site-packages\theano\gof\vm.py", line 674, in <module>
    from . import lazylinker_c
  File "C:\Users\me\Anaconda3\envs\py2\lib\site-packages\theano\gof\lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "C:\Users\me\Anaconda3\envs\py2\lib\site-packages\theano\gof\cmodule.py", line 2411, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): C:\Users\me\AppData\Local\Temp\ccpb51k6.o: In function `unpack_li. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:\Users\me\AppData\Local\Temp\ccpb51k6.o:C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineIntel-2.7.18-64/lazylinker_ext/mod.cpp:397: more undefined references to . C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:\Users\me\AppData\Local\Temp\ccpb51k6.o:C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineIntel-2.7.18-64/lazylinker_ext/mod.cpp:546: more undefined references to . C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:\Users\me\AppData\Local\Temp\ccpb51k6.o:C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineIntel-2.7.18-64/lazylinker_ext/mod.cpp:850: more undefined references to . C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. C:/Users/me/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-Intel64_Family_6_Model_126_Stepping_5_GenuineI. collect2.exe: error: ld returned 1 exit statusined reference to `__imp__Py_TrueStruct'`

**Comment by boblsturm** [comment]
Hi all. You might want to try the pytorch implementation: https://github.com/boblsturm/folkplagiarism
