### ISSUE TITLE
ImportError: cannot import name downsample

### ISSUE THREAD

**Issue by loveJasmine** [IraKorshunova/folk-rnn#4]
rzai@rzai00:~/prj/folk-rnn$ python train_rnn.py 
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Traceback (most recent call last):
  File "train_rnn.py", line 9, in <module>
    import lasagne as nn
  File "/usr/local/lib/python2.7/dist-packages/lasagne/**init**.py", line 19, in <module>
    from . import layers
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/**init**.py", line 7, in <module>
    from .pool import *
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
rzai@rzai00:~/prj/folk-rnn$

**Comment by IraKorshunova** [comment]
I would update Theano and Lasagne

**Comment by loveJasmine** [comment]
update lasagne can fix this issue
